### ISSUE TITLE
Sparse Fields -- JSONAPI

### ISSUE THREAD

**Issue by Kreeby** [MieskeB/json-api-spring-boot#11]
Will this library support Sparse fields? 
For reference: https://jsonapi.org/format/#fetching-sparse-fieldsets

**Comment by MieskeB** [comment]
Hey Kreeby, thanks for the message!

This library is (currently) only for converting dto objects to json:api standard string. It may be possible but I think a lot of code reworking has to be done.

Sparse fields are currently not on the roadmap. If you want to create an implementation for this, you are ofcourse welcome to!
