### ISSUE TITLE
help: basic api-json example

### ISSUE THREAD

**Issue by joekrom** [MieskeB/json-api-spring-boot#16]
HI thx for the initiative,  i would like to have a little bit help, 
i just tried a simple json from the User Model as given as example  and the response json i get is  not what is expected: 
`{"id":"1411","selfRel":null,"allSelfRel":null,"firstRel":null,"lastRel":null,"nextRel":null,"previousRel":null,"relatedRel":null,"username":"john mapamba"}`
that is waht i am geeting back instead of the structure :
`
{
  "data": {
    "attributes": {
      "username": "the username"
    },
    "id": "the id",
    "type": "User"
  },
  "links": {
    "self": "http://localhost:8080/user/the+id"
  }
}`
I would like to know if the mistake  is from mine other should i correct something : 
`@JsonApiObject("User")
public class User  extends JsonApiDtoExtendable {

    private String id;

    @JsonApiProperty
    private String username;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
}` 
the above class  is the one  i used and on the controller side , i just created a basic instance with id and username 
that i tried to display as json .

I am using spring boot 3.0.6 

Any help will be welcomme

**Comment by joekrom** [comment]
Hi @MieskeB , it is working fine with the converter , my Bad
That means we should always render the ResponseEntity as a String .
I am just asking myself if we can not improve it so that when 
using the controller we won't need to convert the object no more 
Thank for the work . it is really intituiv to use

**Comment by MieskeB** [comment]
That is a very good suggestion to which I didn't think of before, I will look into it!

**Comment by MieskeB** [comment]
I will open a new more descriptive issue about this topic and close thisone now. If you have other questions, feel free to open it again.
